# Generated by Django 4.2 on 2023-06-03 11:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_billingaddress_coupon_order_refund_payment_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
