# Generated by Django 4.2 on 2023-07-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_popularitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularItem',
        ),
    ]
